In [54]:
import pandas as pd

## Load data

In [75]:
assets = pd.read_csv("../data/raw_data/assets.csv")
attachments = pd.read_csv("../data/raw_data/attachments.csv")

In [76]:
assets.head()

,Asset ID,Asset Status,Class,Recreation Type,Bundle,Department - Region,Section,Management Area,Park,Park Subarea,...,Number of Steps,Structure Position,"Material (Frame, Tank, Body)",Surface Material,Decking Material,Structure Material,Abutment Material,Has Pedestrian Railing,Has Edge Guard,Bridge Type
0,46340,In Service,Infrastructure,Backcountry,No Bundle,Kootenay Okanagan,Kootenay,East Kootenay South,Akamina-Kishinena Park,Akamina Road To Wall Lake,...,NaN,NaN,Timber/Wood,Wood or Timber,Timber,Timber,Timber,2 railings,No,Beam
1,46341,In Service,Infrastructure,Backcountry,No Bundle,Kootenay Okanagan,Kootenay,East Kootenay South,Akamina-Kishinena Park,Forum Lake Trail,...,NaN,NaN,Timber/Wood,TBD,Timber,Timber,Timber,No railings,No,Beam
2,46342,In Service,Infrastructure,Backcountry,No Bundle,Kootenay Okanagan,Kootenay,East Kootenay South,Akamina-Kishinena Park,Forum Lake Trail,...,NaN,NaN,Timber/Wood,NaN,Timber,Timber,NaN,No railings,No,NaN
3,46496,In Service,Infrastructure,Day Use,Sea-to-Sky,South Coast,Sea-to-Sky,Garibaldi South,Alice Lake Park,South Beach,...,0.0,TBD,Natural Surface,NaN,NaN,NaN,NaN,No railings,NaN,NaN
4,46588,In Service,Infrastructure,Day Use,Central Okanagan/Similkameen,Kootenay Okanagan,Okanagan,West Okanagan,Allison Lake Park,Day-Use,...,-1.0,At-Grade,Rock/Stone,NaN,NaN,NaN,NaN,No railings,NaN,NaN

In [77]:
attachments.head()

,File Name,Module,Source Page Type,Asset ID,Description,File Type,File Size,Uploaded,Category,Segment,Length measured by staff,download folder
0,AST_EX_20240814_102716.jpeg,Assets,Asset,46340,NaN,jpeg,112.46 KB,8/21/2024 10:52,Bridges,Trail Bridge,True,NaN
1,AST_EX_20240814_102658.jpeg,Assets,Asset,46340,NaN,jpeg,101.20 KB,8/21/2024 10:52,Bridges,Trail Bridge,True,NaN
2,AST_EX_20240814_102613.jpeg,Assets,Asset,46340,NaN,jpeg,107.09 KB,8/21/2024 10:52,Bridges,Trail Bridge,True,NaN
3,AST_EX_20240814_102636.jpeg,Assets,Asset,46340,NaN,jpeg,97.73 KB,8/21/2024 10:52,Bridges,Trail Bridge,True,NaN
4,AST_EX_20251210_115555.jpeg,Assets,Asset,46496,NaN,jpeg,137.89 KB,12/10/2025 12:48,Structures,Stairs,True,NaN

### Remove unnecessary columns

In [78]:
attachments = attachments[["File Name", "Asset ID", "Category", "Segment"]]
assets = assets.drop(columns=["Asset Status", "Class", "Recreation Type", "Bundle", "Department - Region", "Section", "Management Area", "Park", "Park Subarea", "Category - Classification", "Segment - Sub Classification"])

## Merge datasets

In [81]:
merged_df = pd.merge(attachments, assets, on="Asset ID", how="left")
print(merged_df.columns)

Index(['File Name', 'Asset ID', 'Category', 'Segment', 'Name', 'Description',
       'Attachments', 'Adjusted Quantity', 'Unit of Measure',
       'In-Service Date', 'All Notes', 'Length (m)', 'length measure by staff',
       'Width (m)', 'Fall Height (m)', 'Height (m)', 'Number of Steps',
       'Structure Position', 'Material (Frame, Tank, Body)',
       'Surface Material', 'Decking Material', 'Structure Material',
       'Abutment Material', 'Has Pedestrian Railing', 'Has Edge Guard',
       'Bridge Type'],
      dtype='object')

In [80]:
merged_df.head()

,File Name,Asset ID,Category,Segment,Name,Description,Attachments,Adjusted Quantity,Unit of Measure,In-Service Date,...,Number of Steps,Structure Position,"Material (Frame, Tank, Body)",Surface Material,Decking Material,Structure Material,Abutment Material,Has Pedestrian Railing,Has Edge Guard,Bridge Type
0,AST_EX_20240814_102716.jpeg,46340,Bridges,Trail Bridge,Trail Bridge,Akamina Road To Wall Lake; Additional notes: n...,4,7,Length (m),1/1/1992,...,NaN,NaN,Timber/Wood,Wood or Timber,Timber,Timber,Timber,2 railings,No,Beam
1,AST_EX_20240814_102658.jpeg,46340,Bridges,Trail Bridge,Trail Bridge,Akamina Road To Wall Lake; Additional notes: n...,4,7,Length (m),1/1/1992,...,NaN,NaN,Timber/Wood,Wood or Timber,Timber,Timber,Timber,2 railings,No,Beam
2,AST_EX_20240814_102613.jpeg,46340,Bridges,Trail Bridge,Trail Bridge,Akamina Road To Wall Lake; Additional notes: n...,4,7,Length (m),1/1/1992,...,NaN,NaN,Timber/Wood,Wood or Timber,Timber,Timber,Timber,2 railings,No,Beam
3,AST_EX_20240814_102636.jpeg,46340,Bridges,Trail Bridge,Trail Bridge,Akamina Road To Wall Lake; Additional notes: n...,4,7,Length (m),1/1/1992,...,NaN,NaN,Timber/Wood,Wood or Timber,Timber,Timber,Timber,2 railings,No,Beam
4,AST_EX_20251210_115555.jpeg,46496,Structures,Stairs,Stairs - South Beach,Alice Lake South Beach; Additional notes: y; I...,2,37,Length (m),1/1/1962,...,0.0,TBD,Natural Surface,NaN,NaN,NaN,NaN,No railings,NaN,NaN

In [72]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5561 entries, 0 to 5560
Data columns (total 27 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   File Name                     5561 non-null   object
 1   Asset ID                      5561 non-null   int64
 2   Category                      5561 non-null   object
 3   Segment                       5561 non-null   object
 4   Length measured by staff      5561 non-null   bool
 5   Name                          5561 non-null   object
 6   Description                   5137 non-null   object
 7   Attachments                   5561 non-null   int64
 8   Adjusted Quantity             5561 non-null   object
 9   Unit of Measure               5561 non-null   object
 10  In-Service Date               5561 non-null   object
 11  All Notes                     2085 non-null   object
 12  Length (m)                    5266 non-null   float64
 13  length measure by staff       5561 non-null   bool
 14  Width (m)                     4145 non-null   float64
 15  Fall Height (m)               5542 non-null   float64
 16  Height (m)                    5299 non-null   float64
 17  Number of Steps               1097 non-null   float64
 18  Structure Position            1332 non-null   object
 19  Material (Frame, Tank, Body)  1967 non-null   object
 20  Surface Material              1029 non-null   object
 21  Decking Material              4349 non-null   object
 22  Structure Material            4345 non-null   object
 23  Abutment Material             2084 non-null   object
 24  Has Pedestrian Railing        5434 non-null   object
 25  Has Edge Guard                3146 non-null   object
 26  Bridge Type                   2043 non-null   object
dtypes: bool(2), float64(5), int64(2), object(18)
memory usage: 1.1+ MB

### Number of unique assets

In [82]:
merged_df['Asset ID'].nunique()

3532

## Creating a dataframe for each asset category

In [83]:
merged_df['Segment'].unique()

array(['Trail Bridge', 'Stairs', 'Boardwalk < 1.2m High',
       'Viewing Platform', 'Boardwalk > 1.2m High'], dtype=object)

In [84]:
merged_df.to_csv("../data/processed/merged_data.csv")

In [85]:
trail_bridges_df = merged_df[merged_df['Segment'] == "Trail Bridge"].reset_index()
trail_bridges_df = trail_bridges_df[["File Name",
                                     "Asset ID",
                                     "Description",
                                     "Abutment Material",
                                     "Bridge Type",
                                     "Decking Material",
                                     "Fall Height (m)",
                                     "Has Pedestrian Railing", 
                                     "Length (m)",
                                     "length measure by staff",
                                     "Structure Material",
                                     "Structure Position",
                                     "Width (m)"]]

In [92]:
trail_bridges_df.info()
trail_bridges_df.to_csv("../data/processed/trail_bridges_df.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1864 entries, 0 to 1863
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   File Name                1864 non-null   object
 1   Asset ID                 1864 non-null   int64
 2   Description              1715 non-null   object
 3   Abutment Material        1794 non-null   object
 4   Bridge Type              1784 non-null   object
 5   Decking Material         1843 non-null   object
 6   Fall Height (m)          1857 non-null   float64
 7   Has Pedestrian Railing   1835 non-null   object
 8   Length (m)               1843 non-null   float64
 9   length measure by staff  1864 non-null   bool
 10  Structure Material       1839 non-null   object
 11  Structure Position       1 non-null      object
 12  Width (m)                1844 non-null   float64
dtypes: bool(1), float64(3), int64(1), object(8)
memory usage: 176.7+ KB

In [95]:
stairs_df = merged_df[merged_df['Segment'] == "Stairs"].reset_index()
stairs_df = stairs_df[["File Name",
                       "Asset ID",
                       "Description",
                       "Abutment Material",
                       "Fall Height (m)",
                       "Has Pedestrian Railing",
                       "Material (Frame, Tank, Body)",
                       "Number of Steps",
                       "Structure Material",
                       "Width (m)"]]

In [97]:
stairs_df.info()
stairs_df.to_csv("../data/processed/stairs_df.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   File Name                     1100 non-null   object
 1   Asset ID                      1100 non-null   int64
 2   Description                   1095 non-null   object
 3   Abutment Material             4 non-null      object
 4   Fall Height (m)               1092 non-null   float64
 5   Has Pedestrian Railing        1083 non-null   object
 6   Material (Frame, Tank, Body)  1100 non-null   object
 7   Number of Steps               1096 non-null   float64
 8   Structure Material            4 non-null      object
 9   Width (m)                     9 non-null      float64
dtypes: float64(3), int64(1), object(6)
memory usage: 86.1+ KB

In [98]:
viewing_platforms_df = merged_df[merged_df['Segment'] == "Viewing Platform"].reset_index()
viewing_platforms_df = viewing_platforms_df[["File Name",
                                             "Asset ID",
                                             "Description",
                                             "Decking Material",
                                             "Fall Height (m)",
                                             "Has Edge Guard",
                                             "Has Pedestrian Railing",
                                             "Length (m)",
                                             "length measure by staff",
                                             "Structure Material",
                                             "Structure Position",
                                             "Width (m)"]]

In [104]:
viewing_platforms_df.info()
viewing_platforms_df.to_csv("../data/processed/viewing_platforms_df.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2222 entries, 0 to 2221
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   File Name                2222 non-null   object
 1   Asset ID                 2222 non-null   int64
 2   Description              1982 non-null   object
 3   Decking Material         2126 non-null   object
 4   Fall Height (m)          2218 non-null   float64
 5   Has Edge Guard           1950 non-null   object
 6   Has Pedestrian Railing   2142 non-null   object
 7   Length (m)               2027 non-null   float64
 8   length measure by staff  2222 non-null   bool
 9   Structure Material       2128 non-null   object
 10  Width (m)                1925 non-null   float64
dtypes: bool(1), float64(3), int64(1), object(6)
memory usage: 175.9+ KB

In [102]:
low_boardwalks_df = merged_df[merged_df['Segment'] == "Boardwalk < 1.2m High"].reset_index()
low_boardwalks_df = low_boardwalks_df[["File Name",
                                       "Asset ID",
                                       "Description",
                                       "Decking Material",
                                       "Fall Height (m)",
                                       "Has Edge Guard",
                                       "Has Pedestrian Railing",
                                       "Length (m)",
                                       "length measure by staff",
                                       "Structure Material",
                                       "Width (m)"]]

In [105]:
low_boardwalks_df.info()
low_boardwalks_df.to_csv("../data/processed/low_boardwalks_df.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2222 entries, 0 to 2221
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   File Name                2222 non-null   object
 1   Asset ID                 2222 non-null   int64
 2   Description              1982 non-null   object
 3   Decking Material         2126 non-null   object
 4   Fall Height (m)          2218 non-null   float64
 5   Has Edge Guard           1950 non-null   object
 6   Has Pedestrian Railing   2142 non-null   object
 7   Length (m)               2027 non-null   float64
 8   length measure by staff  2222 non-null   bool
 9   Structure Material       2128 non-null   object
 10  Width (m)                1925 non-null   float64
dtypes: bool(1), float64(3), int64(1), object(6)
memory usage: 175.9+ KB

In [106]:
elevated_boardwalks_df = merged_df[merged_df['Segment'] == "Boardwalk > 1.2m High"].reset_index()
elevated_boardwalks_df = elevated_boardwalks_df[["File Name",
                                                 "Asset ID",
                                                 "Description",
                                                 "Decking Material",
                                                 "Fall Height (m)",
                                                 "Has Edge Guard",
                                                 "Has Pedestrian Railing",
                                                 "Length (m)",
                                                 "length measure by staff",
                                                 "Structure Material",
                                                 "Width (m)"]]

In [107]:
elevated_boardwalks_df.info()
elevated_boardwalks_df.to_csv("../data/processed/elevated_boardwalks_df.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   File Name                145 non-null    object
 1   Asset ID                 145 non-null    int64
 2   Description              135 non-null    object
 3   Decking Material         144 non-null    object
 4   Fall Height (m)          145 non-null    float64
 5   Has Edge Guard           133 non-null    object
 6   Has Pedestrian Railing   144 non-null    object
 7   Length (m)               87 non-null     float64
 8   length measure by staff  145 non-null    bool
 9   Structure Material       144 non-null    object
 10  Width (m)                144 non-null    float64
dtypes: bool(1), float64(3), int64(1), object(6)
memory usage: 11.6+ KB