In [1]:
import pandas as pd

## Load data

In [21]:
assets = pd.read_csv("../data/raw_data/assets.csv")
attributes = pd.read_csv("../data/raw_data/attributes.csv")

In [22]:
assets.head()

,File Name,Module,Source Page Type,Asset ID,Description,File Type,File Size,Uploaded,Category,Segment
0,AST_EX_20240814_102716.jpeg,Assets,Asset,46340,NaN,jpeg,112.46 KB,8/21/2024 10:52,Bridges,Trail Bridge
1,AST_EX_20240814_102658.jpeg,Assets,Asset,46340,NaN,jpeg,101.20 KB,8/21/2024 10:52,Bridges,Trail Bridge
2,AST_EX_20240814_102613.jpeg,Assets,Asset,46340,NaN,jpeg,107.09 KB,8/21/2024 10:52,Bridges,Trail Bridge
3,AST_EX_20240814_102636.jpeg,Assets,Asset,46340,NaN,jpeg,97.73 KB,8/21/2024 10:52,Bridges,Trail Bridge
4,AST_EX_20251210_115555.jpeg,Assets,Asset,46496,NaN,jpeg,137.89 KB,12/10/2025 12:48,Structures,Stairs

In [23]:
attributes.head()

,Asset ID,Asset Status,Class,Recreation Type,Bundle,Department - Region,Section,Management Area,Park,Park Subarea,...,Number of Steps,Structure Position,"Material (Frame, Tank, Body)",Surface Material,Decking Material,Structure Material,Abutment Material,Has Pedestrian Railing,Has Edge Guard,Bridge Type
0,46340,In Service,Infrastructure,Backcountry,No Bundle,Kootenay Okanagan,Kootenay,East Kootenay South,Akamina-Kishinena Park,Akamina Road To Wall Lake,...,NaN,NaN,Timber/Wood,Wood or Timber,Timber,Timber,Timber,2 railings,No,Beam
1,46341,In Service,Infrastructure,Backcountry,No Bundle,Kootenay Okanagan,Kootenay,East Kootenay South,Akamina-Kishinena Park,Forum Lake Trail,...,NaN,NaN,Timber/Wood,TBD,Timber,Timber,Timber,No railings,No,Beam
2,46342,In Service,Infrastructure,Backcountry,No Bundle,Kootenay Okanagan,Kootenay,East Kootenay South,Akamina-Kishinena Park,Forum Lake Trail,...,NaN,NaN,Timber/Wood,NaN,Timber,Timber,NaN,No railings,No,NaN
3,46496,In Service,Infrastructure,Day Use,Sea-to-Sky,South Coast,Sea-to-Sky,Garibaldi South,Alice Lake Park,South Beach,...,0.0,TBD,Natural Surface,NaN,NaN,NaN,NaN,No railings,NaN,NaN
4,46588,In Service,Infrastructure,Day Use,Central Okanagan/Similkameen,Kootenay Okanagan,Okanagan,West Okanagan,Allison Lake Park,Day-Use,...,-1.0,At-Grade,Rock/Stone,NaN,NaN,NaN,NaN,No railings,NaN,NaN

### Remove unnecessary columns

In [24]:
assets = assets[["File Name", "Asset ID", "Category", "Segment"]]
attributes = attributes.drop(columns=["Asset Status", "Class", "Recreation Type", "Bundle", "Department - Region", "Section", "Management Area", "Park", "Park Subarea", "Category - Classification", "Segment - Sub Classification"])

In [25]:
merged_df = pd.merge(assets, attributes, on="Asset ID", how="left")

In [26]:
merged_df.head()

,File Name,Asset ID,Category,Segment,Name,Description,Attachments,Adjusted Quantity,Unit of Measure,In-Service Date,...,Number of Steps,Structure Position,"Material (Frame, Tank, Body)",Surface Material,Decking Material,Structure Material,Abutment Material,Has Pedestrian Railing,Has Edge Guard,Bridge Type
0,AST_EX_20240814_102716.jpeg,46340,Bridges,Trail Bridge,Trail Bridge,Akamina Road To Wall Lake; Additional notes: n...,4,7,Length (m),1/1/1992,...,NaN,NaN,Timber/Wood,Wood or Timber,Timber,Timber,Timber,2 railings,No,Beam
1,AST_EX_20240814_102658.jpeg,46340,Bridges,Trail Bridge,Trail Bridge,Akamina Road To Wall Lake; Additional notes: n...,4,7,Length (m),1/1/1992,...,NaN,NaN,Timber/Wood,Wood or Timber,Timber,Timber,Timber,2 railings,No,Beam
2,AST_EX_20240814_102613.jpeg,46340,Bridges,Trail Bridge,Trail Bridge,Akamina Road To Wall Lake; Additional notes: n...,4,7,Length (m),1/1/1992,...,NaN,NaN,Timber/Wood,Wood or Timber,Timber,Timber,Timber,2 railings,No,Beam
3,AST_EX_20240814_102636.jpeg,46340,Bridges,Trail Bridge,Trail Bridge,Akamina Road To Wall Lake; Additional notes: n...,4,7,Length (m),1/1/1992,...,NaN,NaN,Timber/Wood,Wood or Timber,Timber,Timber,Timber,2 railings,No,Beam
4,AST_EX_20251210_115555.jpeg,46496,Structures,Stairs,Stairs - South Beach,Alice Lake South Beach; Additional notes: y; I...,2,37,Length (m),1/1/1962,...,0.0,TBD,Natural Surface,NaN,NaN,NaN,NaN,No railings,NaN,NaN

In [27]:
merged_df.describe()

,Asset ID,Attachments,Length (m),Width (m),Fall Height (m),Height (m),Number of Steps
count,5561.000000,5561.000000,5266.000000,4145.000000,5542.000000,5299.000000,1097.000000
mean,93639.324942,2.655458,23.100657,1.149626,-0.694262,0.776265,-0.085688
std,22893.935907,2.703377,118.464110,2.698973,3.600445,8.154599,5.290291
min,46340.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,83951.000000,1.000000,3.000000,0.500000,-1.000000,0.000000,-1.000000
50%,94320.000000,2.000000,7.500000,1.000000,-1.000000,0.000000,-1.000000
75%,111691.000000,3.000000,17.000000,1.200000,-1.000000,1.000000,-1.000000
max,129760.000000,20.000000,5000.000000,115.000000,125.000000,400.000000,96.000000

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5561 entries, 0 to 5560
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   File Name                     5561 non-null   object
 1   Asset ID                      5561 non-null   int64
 2   Category                      5561 non-null   object
 3   Segment                       5561 non-null   object
 4   Name                          5561 non-null   object
 5   Description                   5137 non-null   object
 6   Attachments                   5561 non-null   int64
 7   Adjusted Quantity             5561 non-null   object
 8   Unit of Measure               5561 non-null   object
 9   In-Service Date               5561 non-null   object
 10  All Notes                     2085 non-null   object
 11  Length (m)                    5266 non-null   float64
 12  Width (m)                     4145 non-null   float64
 13  Fall Height (m)               5542 non-null   float64
 14  Height (m)                    5299 non-null   float64
 15  Number of Steps               1097 non-null   float64
 16  Structure Position            1332 non-null   object
 17  Material (Frame, Tank, Body)  1967 non-null   object
 18  Surface Material              1029 non-null   object
 19  Decking Material              4349 non-null   object
 20  Structure Material            4345 non-null   object
 21  Abutment Material             2084 non-null   object
 22  Has Pedestrian Railing        5434 non-null   object
 23  Has Edge Guard                3146 non-null   object
 24  Bridge Type                   2043 non-null   object
dtypes: float64(5), int64(2), object(18)
memory usage: 1.1+ MB